USE ShareYourMedia;

SHOW VARIABLES LIKE "secure_file_priv";

LOAD DATA INFILE 'csv/users.csv'
    INTO TABLE REGULAR_USER
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

LOAD DATA INFILE 'csv/admins.csv'
    INTO TABLE ADMIN_USER
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

LOAD DATA INFILE 'csv/episodes.csv'
    INTO TABLE MEDIAFILE
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

LOAD DATA INFILE 'csv/songs.csv'
    INTO TABLE MEDIAFILE
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

LOAD DATA INFILE 'csv/categorychangers.csv'
    INTO TABLE CUSTOM_CATEGORY
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

LOAD DATA INFILE 'csv/uploaders.csv'
    INTO TABLE UPLOAD
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

LOAD DATA INFILE 'csv/categories.csv'
    INTO TABLE DEFAULT_CATEGORIES
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

INSERT INTO PLAYLIST (name, creator, criteria)
VALUES ('Tastebreakers', 'nelson@uminho.pt', 'random');

LOAD DATA INFILE 'csv/playlists.csv'
    INTO TABLE PLAYLIST_has_MEDIAFILE
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;

